workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2 # Opsional: bisa dihapus jika tidak butuh Mac (Android bisa pakai linux), tapi Mac lebih stabil untuk Flutter
    environment:
      flutter: stable # <--- INI YANG PENTING: Menentukan versi Flutter
      vars:
        # Hapus JAVA_HOME, Codemagic akan otomatis mendeteksi
        FLUTTER_VERSION: "3.19.0" # Sesuaikan dengan versi lokal Anda
      groups:
        - android_credentials # <--- Opsional: Jika Anda menyimpan keystore/API di Codemagic UI
    scripts:
      - name: Setup Flutter
        script: |
          flutter config --no-analytics
          flutter pub get
          
      - name: Build APK
        script: |
          flutter build apk --release --split-per-abi
          
    artifacts:
      - build/**/*.apk
